name: desktop_entry
description: A Dart package for managing Desktop Entry files (.desktop) and DBus Service files in
  Linux environments.
version: 1.0.1+1
homepage: https://markvideon.dev

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  collection: ^1.16.0
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.1
  path_provider: ^2.0.11
  test: ^1.21.4
  xdg_directories: ^0.2.0+2

  # Some tests make use of [path_provider] to access a temporary directory, which depends on the
  # Flutter SDK.
  flutter:
    sdk: flutter

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# This package supports only Linux.
platforms:
  linux:
