name: desktop_entry
description: A Flutter plugin for managing Desktop Entry files (.desktop) and DBus Service files in
  Linux environments.
version: 1.0.0
homepage: https://markvideon.dev

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  collection: ^1.16.0
  flutter_platform_alert: ^0.3.0
  path: ^1.8.2
  path_provider: ^2.0.10
  xdg_directories: ^0.2.0+2

dev_dependencies:
  test: ^1.21.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# This package supports only Linux.
platforms:
  linux:
